#ifndef DATA_ENUMS_H
#define DATA_ENUMS_H

enum CarState
{
    CAR_MAPPING,
    CAR_ENC_READING,
    CAR_ENC_READING_BEFORE_FIRSTMARK,
    CAR_TUNING,
    CAR_STOPPED,
};


enum DataFunction
{
    RETORNO_OK,
    RETORNO_ERRO,
    RETORNO_ERRO_GENERICO,
    RETORNO_ARGUMENTO_INVALIDO,
    RETORNO_VARIAVEL_OCUPADA
};

#endif